language: generic

sudo: required

services:
  - docker

script:
  - |
    docker run \
        --rm \
        --workdir /ngtc \
        --volume ${TRAVIS_BUILD_DIR}:/ngtc \
        tpimh/ngtc:latest /bin/sh -c 'root/sync.sh && root/configure.sh && root/build.sh && root/install.sh'
