language: generic

sudo: required

jobs:
  include:
    - stage: configure
      script: ./build-all.sh configure
    - stage: build
      script: ./build-all.sh build
    - stage: install
      script: ./build-all.sh install
